#!/bin/sh

pandoc -s -t revealjs $1.md -o $1.html -V theme=ime -V transition=fade --mathjax --slide-level 1 --template=../template.html --bibliography=../../bib/library.bib --csl=/home/acmt/Documentos/git/styles/ieeeBraces.csl

